### ISSUE TITLE
Recipe of Poison Spears

### ISSUE THREAD

**Issue by Awar2k** [island-troll-tribes/island-troll-tribes#101]
Update the recipe of Poison Spears to be more consistent with other spears.
Add Quick Make to poison spears in WS.

**Comment by jonathanmclaus** [comment]
What is inconsistent about this? What should the recipe be?

**Comment by Awar2k** [comment]
I believe Snap felt as though the Poison should go first as the first item determines the quality of the spear. (Stone, Iron, Steel)

**Comment by Bliss-Darkeyes** [comment]
No arguments here, as long as it’s captured in all the recipe changes, I can get this one when I’m back

**Comment by Jaccouille** [comment]
[I changed the recipe](https://github.com/island-troll-tribes/island-troll-tribes/pull/313/commits/b52f3731880c2c5506a0ae93ff9e2b0e915f75f6)
