### ISSUE TITLE
Mud Hut Quick Drop

### ISSUE THREAD

**Issue by Awar2k** [island-troll-tribes/island-troll-tribes#102]
Give Mud Hut the ability to quick drop to a unit.

**Comment by DavidPalmgren** [comment]
no

**Comment by Awar2k** [comment]
I updated the issue, it was intended to be a quick drop to a unit, not to the ground.

**Comment by LiquidSwordz** [comment]
I might be late here, but this seems like an unnecessary buff to mud hut

**Comment by theQuazz** [comment]
We've discussed this before in the council. From a balance perspective our opinion is generally negative. From a usability perspective I personally like it, though I may suggest adding it to storage hut instead of mud hut. Thus, for the time being, I'll close this.
