### ISSUE TITLE
Sharing Gold Command

### ISSUE THREAD

**Issue by Awar2k** [island-troll-tribes/island-troll-tribes#105]
Options:
Add a game-mode to allow a team to have a shared gold amount.
Add an in-game command "-team gold" "-tg" where you opt-in to a shared gold amount.
Add an in-game command "-solo gold" "-sg" where you opt-out of a shared gold amount.

**Comment by Marsunpaisti** [comment]
Im pretty sure this is not possible without custom gold mechanics

**Comment by theQuazz** [comment]
@Marsunpaisti it is possible, but we'd need to build a system for it

**Comment by Jaccouille** [comment]
Maybe we can close this? #264

**Comment by theQuazz** [comment]
@Jaccouille yes good call
