### ISSUE TITLE
Fix These Tooltips

### ISSUE THREAD

**Issue by Awar2k** [island-troll-tribes/island-troll-tribes#121]
Check all comments for tooltips to fix.

**Comment by Jaccouille** [comment]
Armory quick make tool tips make mention of -i am noob command
Pinions of shadow tooltip (I didn't check others) says "Binds when equiped" when it is actually droppable
Hydra fyns tooltip says it give + 4 armor and has a phase ability, while it give +22.5 armor and has spellshield

**Comment by Awar2k** [comment]
GoK updated to say that it works with thief.

**Comment by Jaccouille** [comment]
GoK has been updated

**Comment by Woodenplank** [comment]
Tannery abilities (gloves, coat, boots) still mention "panther hide" which doesn't exist.

**Comment by Awar2k** [comment]
Acorn tooltip to say 38 health.

**Comment by Jaccouille** [comment]
![](https://i.gyazo.com/725dc73bcb6358e93bcca19a2338eabf.png)

**Comment by Jaccouille** [comment]
battle glove recipe on bottom island
