### ISSUE TITLE
BM revamp: create object definitions for pets

### ISSUE THREAD

**Issue by Marsunpaisti** [island-troll-tribes/island-troll-tribes#178]
We need wurst object definitions for the tamed hero-pets (and the druid itself) and corresponding wurst UnitObjects for the units

**Elk - In progress**
Wolf
Bear

**Comment by Marsunpaisti** [comment]
Some base framework for pets laid out in my Pet utilities PR. Created elk pet definition & tested that taming system works

**Comment by jonathanmclaus** [comment]
BM was reworked into shaman.
