### ISSUE TITLE
Override Game Constant for Troll Cursor

### ISSUE THREAD

**Issue by jonathanmclaus** [island-troll-tribes/island-troll-tribes#255]
#254 directly overwrites the file for the Human cursor. We should instead introduce a new file and change the UI constant.

**Comment by Jaccouille** [comment]
I've extracted the war3mapSkin.txt and war3mapMisc.txt, there is a "Cursor" field in the UI constant, can't test it atm since map doesn't compile.

**Comment by Jaccouille** [comment]
Do you mind removing the troll cursor? I thought it was a nice/funny touch, but players have been complaining that it's harder to do a precise click compared to the undead cursor and I kinda understand, more over, I realized I don't pay any attention to cursor, I guess other player feel the same.

**Comment by jonathanmclaus** [comment]
Closed by #771
