### ISSUE TITLE
Alltroll mode doesnt work

### ISSUE THREAD

**Issue by Marsunpaisti** [island-troll-tribes/island-troll-tribes#286]
All troll doesnt seem to work properly. Someone got a different class even though the mode was -all gatherer.

Game also printed "All all gatherer enabled" when applying the mode

**Comment by Jaccouille** [comment]
![Error](https://i.gyazo.com/1364482ff29178ee71457814f5c15c26.jpg)
![Code](https://i.gyazo.com/244bed5b095a3daec668f6404d4dc86f.png)

**Comment by jonathanmclaus** [comment]
Fixed by #441 by introducing new ID registration.
