### ISSUE TITLE
Potential bone blocking issue

### ISSUE THREAD

**Issue by HallerJohn** [island-troll-tribes/island-troll-tribes#402]

**Comment by SebastianBIL** [comment]
![image](https://user-images.githubusercontent.com/56095738/66085780-78f70d80-e572-11e9-8d04-9e86ddfea5b5.png)

**Comment by SebastianBIL** [comment]
[LastReplay.zip](https://github.com/island-troll-tribes/island-troll-tribes/files/3683600/LastReplay.zip)

**Comment by HallerJohn** [comment]
issue resolved, no bug with bones. was due to bad pathing on ne island.
