### ISSUE TITLE
Meat system

### ISSUE THREAD

**Issue by Mephistophelesss** [island-troll-tribes/island-troll-tribes#447]
So far the feedback i get from new player is that the meat system is finicky. I saw new players just leaving because they don't understand it, maybe it's not explained well enough.

What do you guys think about a auto loot system, where you have to secure the dead animal to get the corpse with an interval of 0.5 sec per corpse?
We could also change so that when you use cook ability on the fire it would drop the corpse automatically and cook it.

Would make the new players experience much more pleasant don't you think? I agree it would remove a lot of the corpse management skill from the game but it's a fair trade in my opinion.

Tell me what you guys think about it.

**Comment by jonathanmclaus** [comment]
I addressed some of the finickiness with a recent update that hasn't been released so hopefully that will fix some of the issues. The biggest problems I see with new players (other than them not understanding it all) is that they switch from grabbing to dropping and then undo their previous action. That's prevented now.

I think having a gameplay per setting of having a fire cook corpses that you're currently carrying would be OK. I don't foresee anyone getting an unfair advantage from that if the cooked meat is still dropped on the ground.

**Comment by Mephistophelesss** [comment]
> I addressed some of the finickiness with a recent update that hasn't been released so hopefully that will fix some of the issues. The biggest problems I see with new players (other than them not understanding it all) is that they switch from grabbing to dropping and then undo their previous action. That's prevented now.
> 
> I think having a gameplay setting per playing of having a fire cook corpses that you're currently carrying would be OK. I don't foresee anyone getting an unfair advantage from that if the cooked meat is still dropped on the ground.

I really like what you did by temporarily disabling the spell after switching, and to be honest I really like how the meat system is right now. I think the main issue is that brand new players don't know that they need to pick up meat at all, they just grab all the items it drops and then leave the meat there.

**Comment by jonathanmclaus** [comment]
We could also have more aggressive hints by printing them (and maybe even giving orders) in response to certain events, rather than just on a timed loop.
