### ISSUE TITLE
Killing hydra triggers an error

### ISSUE THREAD

**Issue by Jaccouille** [island-troll-tribes/island-troll-tribes#475]
![](https://i.gyazo.com/c4399a6dab21330213e86377acb8592c.jpg)

**Comment by jonathanmclaus** [comment]
Fixed by #509

**Comment by jonathanmclaus** [comment]
![image](https://user-images.githubusercontent.com/5731591/79348519-17413400-7f03-11ea-8397-759157b55ac2.png)

Still broken as of 3.6
