### ISSUE TITLE
Troll getting slowed indefinitely

### ISSUE THREAD

**Issue by Jaccouille** [island-troll-tribes/island-troll-tribes#482]
I played a game, two of my teammate went into a fight, they went into a fight including unsub gatherer, mage and thief. When they came back, they had the slow debuff, the one given by negative blast/metronome, I didn't watch the fight and forgot to save replay, they got slowed for the whole game.

My guess is on gatherer armor salve, it's based off frost armor so I bet it can give the debuff, will check it out.

**Comment by jonathanmclaus** [comment]
Fixed by #509
