### ISSUE TITLE
Re-enable customs skins

### ISSUE THREAD

**Issue by Jaccouille** [island-troll-tribes/island-troll-tribes#507]
When I reworked the troll unit definition, I purposely didn't rewrote the units having a custom skins because I was too lazy/think it was just stupid in the first place, but Mambo want his skin back so I'll make an effort.

**Comment by jonathanmclaus** [comment]
I think there's more work that needs to be done first. I see some problems where unit type is checked and that would be incorrect if we added more skins. For example, I think that telegathering used to check the unit type to see if herbs could be gatherered. It does it the correct way now by checking buffs and parameters, but there might be other abilities that check exact unit types incorrectly.

**Comment by jonathanmclaus** [comment]
The unit type is still checked manually for creating Entities and there are checks based on those, so that's one consideration.

**Comment by Jaccouille** [comment]
Fixed in #588
