### ISSUE TITLE
Super-Subclass Level Requirement Changes

### ISSUE THREAD

**Issue by winkint** [island-troll-tribes/island-troll-tribes#513]
Discussed adjusting of Super-Subclass Level Requirements for the following classes: Omni-Gatherer changes from requiring Level 9 to Level 8; Assassin, Spy, Dementia Master, and Sage changes from requiring level 9 to level 7; Juggernaut and Ultimate Form (BM) stay the same. Changes were discussed according to balancing purposes to allow other classes to have priority for hostile and/or experience funneling.

**Comment by jonathanmclaus** [comment]
Closed by #510
