### ISSUE TITLE
Mode Board got mode missing/useless mode displayed

### ISSUE THREAD

**Issue by Jaccouille** [island-troll-tribes/island-troll-tribes#519]
I realized -fast was missing from the mode board and -tf is displayed twice when it's never used.
Should clean up the board a bit, also some one reported that -nt wasn't working, might want to check out all the modes to see if they work as intended.

![](https://i.gyazo.com/5a9bd581bc3b19817ab114befaa8b884.png)

**Comment by jonathanmclaus** [comment]
Do you know if Warcraft 3 supports having multiple multiboards at once now?

**Comment by Mephistophelesss** [comment]
https://www.hiveworkshop.com/threads/ui-showing-3-multiboards.316610/

**Comment by jonathanmclaus** [comment]
Closed by #530
