### ISSUE TITLE
Elk (and possibly other pets) cannot damage Mammoth

### ISSUE THREAD

**Issue by jonathanmclaus** [island-troll-tribes/island-troll-tribes#554]
The elk pet can attack the mammoth but will do no damage, regardless of how much base damage the pet has.

**Comment by Jaccouille** [comment]
This is due to the` Combat - Damage Bonus Table - Pierce`, it has been changed to 0% against medium armor, Elk deal pierce damage and mammoth got medium armor.

![url](https://i.gyazo.com/c2937b40366f9310d48d4198b5a1f591.png)

**Comment by jonathanmclaus** [comment]
This is problem a "fix" for preventing Mammoth being killed by ensnare traps and towers. I don't think we need to worry about that anymore as long as there's no way to trap and glitch its pathing.

**Comment by jonathanmclaus** [comment]
Fixed by #561
