### ISSUE TITLE
Issue with canopy tree

### ISSUE THREAD

**Issue by Jaccouille** [island-troll-tribes/island-troll-tribes#571]
I noticed while making custom abilities interacting with trees using forDestructablesInRange, that canopy tree destructable returns multiple instance of the same destructable, I believe this may have caused issue with forest fire fx dropping player years ago.

In this gif, I casted a spell that burn the destructable, save it in a HashMap, then replace it with a rotten tree, as you can see the tree behind, which is a canopy tree, is burned multiple time & has multiple rotten tree spawning.
![](https://i.imgur.com/JmYK6fd.gif)

I suggest removing canopy tree from the map to avoid further issue, there's 224 instances of those.

**Comment by jonathanmclaus** [comment]
Canopy Tree has a mechanical difference - it has a 1x1 pathing map instead of 2x2. So removing it would change the game in areas.

Are you sure it wasn't the code that is the problem? If you have an example, that would be helpful.

**Comment by Jaccouille** [comment]
Oh yeah, a big mistake I made in my condition, nevermind then. I thought it was an issue with the trees, when you delete normal trees destructible it crashes the editor.
