### ISSUE TITLE
Priest Fixes

### ISSUE THREAD

**Issue by Awar2k** [island-troll-tribes/island-troll-tribes#90]
Important:
Sage needs AMs
Sage needs Cure All / Omnicure

Quality of Life:
Preserve All doesn't work (Self Preserve inside Gate) - It has no effect even on self. (Sage)
Replenish health will stop working after using Self Preserve but continue to drain mana. (Sage and MH)

Optional:
Add Magic Mist to Master Healer and Sage.

**Comment by Bliss-Darkeyes** [comment]
Will review sage and dm spells when I’m home in about 2 weeks

**Comment by Marsunpaisti** [comment]
All other issues addressed except:
Quality of Life:
Preserve All doesn't work (Self Preserve inside Gate) - It has no effect even on self. (Sage)

**Comment by Jaccouille** [comment]
Fixed in #350
